version: 0.0.2
config:
    project:
        name: polymarket-clob
        version: 0.1.0
        context: devnet
        project_uuid: 2ee9d5df-a6de-4a86-8fc9-d2a264d44e80
        telemetry_enabled: false
        templateBaseUrl: https://github.com/Layr-Labs/hourglass-avs-template
        templateVersion: v0.0.13
